# Variables pour le groupe vintage_story

# Configuration réseau (chargée depuis vars/)
# vs_server_ip et vs_port sont définis dans ansible/vars/production.yml

# Configuration serveur personnalisable
vs_server_name: '[FR] Petites Pousses'
vs_server_description: Serveur Vintage Story des Petites Pousses
vs_welcome_message: Bienvenue {0}, puissiez-vous survivre et prospérer.
vs_max_clients: 4
vs_language: fr
vs_advertise_server: false

# Configuration du monde
vs_world_name: Petites Pousses
vs_world_save_name: petites-pousses
vs_world_seed: 1411521110
