# Inventaire Ansible

vps:
  hosts:
    # VPS - Variables chargées depuis vars/
    vps_server:
      ansible_host: '{{ vps_ip }}'
      ansible_user: debian
      ansible_ssh_private_key_file: ~/.ssh/ovh-vps
      ansible_port: '{{ vps_ssh_port }}'

vintage_story:
  hosts:
    # VPS - Variables chargées depuis vars/
    vps_server:
      ansible_host: '{{ vps_ip }}'
      ansible_user: debian
      ansible_ssh_private_key_file: ~/.ssh/ovh-vps
      ansible_port: '{{ vps_ssh_port }}'

minecraft:
  hosts:
    # VPS - Variables chargées depuis vars/
    vps_server:
      ansible_host: '{{ vps_ip }}'
      ansible_user: debian
      ansible_ssh_private_key_file: ~/.ssh/ovh-vps
      ansible_port: '{{ vps_ssh_port }}'

local:
  hosts:
    localhost:
      ansible_connection: local

all:
  vars:
    # Variables communes
    ansible_python_interpreter: /usr/bin/python3
