---
# Collections Ansible requises pour les playbooks
collections:
  - name: community.general
    # https://galaxy.ansible.com/ui/repo/published/community/general/
    version: 12.2.0
    source: https://galaxy.ansible.com
